language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
#  - "3.8-dev"  # 3.8 development branch

install:
  - pip install pytest pytest-cov flake8
  - pip install codecov
  - pip install .

script:
  - flake8 --count
  - pytest --cov=./

jobs:
  include:
    - stage: "Send notification"
      python: "3.6"
      script:
        - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
        - chmod +x send.sh
        - ./send.sh success $WEBHOOK_URL

#after_success:
#  - codecov

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL