language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install:
  - pip install pytest pytest-cov
  - pip install codecov
  - pip install .
before_script:
  - flake8 --count
script:
  - pytest --cov=./
after_success:
  - codecov