language: python
#python:
#  - "3.4"
#  - "3.5"
#  - "3.6"
#  - "3.7"
#  - "3.8"
#  - "3.8-dev"  # 3.8 development branch
install:
  - pip install pytest pytest-cov flake8
  - pip install codecov
  - pip install .

jobs:
  include:
    - stage: "Code Quality Review"
      script: flake8 --count
    - stage: "Code Tests"
    - python: "3.4"
    - python: "3.5"
      script: pytest --cov=./
      - codecov
    - stage: "Code Coverage"
    - stage: "Send notifications"
      script: wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
              chmod +x send.sh
              ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL